version: '3.4'

services:
  alejandria:
    build:
      context: .
      dockerfile: DockerfileTest
    container_name: alejandria_test
    hostname: alejandria          
    depends_on:
      - postgres 
    
  postgres:
    image: postgres:14
    restart: unless-stopped
    container_name: db_test
    volumes:      
      - ./tests/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 54321:5432
