FROM python:3.8

WORKDIR /app

COPY requirements.txt /tmp/
RUN pip install -r /tmp/requirements.txt

COPY setup setup
COPY gunicorn.conf.py gunicorn.conf.py
COPY shared shared
COPY fakes fakes

EXPOSE 5000

CMD [ "gunicorn" ]
