XML_TEST_ACCOUNTS = """<?xml version="1.0" encoding = "ISO-8859-1"?>
    <Respuesta xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/Respuesta.xsd">
    <Personas>
        <Persona>
            <Encabezado>
                <FolioConsultaOtorgante>00HXQ2PPP23237220104003</FolioConsultaOtorgante>
                <ClaveOtorgante>000997</ClaveOtorgante><ExpedienteEncontrado>1</ExpedienteEncontrado>
                <FolioConsulta>876657434</FolioConsulta>
            </Encabezado>
            <Nombre>
                <ApellidoPaterno>PRUEBA</ApellidoPaterno>
                <ApellidoMaterno>PRUEBA</ApellidoMaterno>
                <ApellidoAdicional></ApellidoAdicional>
                <Nombres>LIDIA</Nombres>
                <FechaNacimiento>1981-01-10</FechaNacimiento>
                <RFC>OMMN9444053L6</RFC>
                <CURP>OMMN944405MDFRDN05</CURP>
                <Nacionalidad></Nacionalidad>
                <Residencia>5</Residencia>
                <EstadoCivil></EstadoCivil>
                <Sexo></Sexo>
                <ClaveElectorIFE></ClaveElectorIFE>
                <NumeroDependientes>2</NumeroDependientes>
                <FechaDefuncion></FechaDefuncion>
            </Nombre>
            <Domicilios>
                <Domicilio>
                    <Direccion>CDA MONTE DE LOS SAUCES</Direccion>
                    <ColoniaPoblacion>jesus del monte</ColoniaPoblacion>
                    <DelegacionMunicipio>CUAJIMALPA</DelegacionMunicipio>
                    <Ciudad>MEXICO</Ciudad>
                    <Estado>DF</Estado>
                    <CP>22891</CP>
                    <FechaResidencia>2022-01-04</FechaResidencia>
                    <NumeroTelefono></NumeroTelefono>
                    <TipoDomicilio></TipoDomicilio>
                    <TipoAsentamiento></TipoAsentamiento>
                    <FechaRegistroDomicilio>2022-01-04</FechaRegistroDomicilio>
                </Domicilio>
                <Domicilio>
                    <Direccion>C SN BORJA 119 </Direccion>
                    <ColoniaPoblacion>JOSEFA ORTIZ DE DOMINGUEZ</ColoniaPoblacion>
                    <DelegacionMunicipio>ENSENADA</DelegacionMunicipio>
                    <Ciudad></Ciudad>
                    <Estado>BC</Estado>
                    <CP>22891</CP>
                    <FechaResidencia>2021-06-24</FechaResidencia>
                    <NumeroTelefono></NumeroTelefono>
                    <TipoDomicilio></TipoDomicilio>
                    <TipoAsentamiento>0</TipoAsentamiento>
                    <FechaRegistroDomicilio>2021-06-24</FechaRegistroDomicilio>
                </Domicilio>
                <Domicilio>
                    <Direccion>C SAN BORJA 119</Direccion>
                    <ColoniaPoblacion>COL JOSEFA ORTIZ DE DOMINGUEZ</ColoniaPoblacion>
                    <DelegacionMunicipio>ENSENADA B C</DelegacionMunicipio>
                    <Ciudad></Ciudad>
                    <Estado>BC</Estado>
                    <CP>22891</CP>
                    <FechaResidencia>2018-04-15</FechaResidencia>
                    <NumeroTelefono></NumeroTelefono>
                    <TipoDomicilio></TipoDomicilio>
                    <TipoAsentamiento>0</TipoAsentamiento>
                    <FechaRegistroDomicilio>2022-04-15</FechaRegistroDomicilio>
                </Domicilio>
                <Domicilio>
                    <Direccion>INSURGENTES SUR 1007</Direccion>
                    <ColoniaPoblacion>INSURGENTES</ColoniaPoblacion>
                    <DelegacionMunicipio>BENITO JUAREZ</DelegacionMunicipio>
                    <Ciudad>BENITO JUAREZ</Ciudad>
                    <Estado>BC</Estado>
                    <CP>22891</CP>
                    <FechaResidencia>2018-04-15</FechaResidencia>
                    <NumeroTelefono></NumeroTelefono>
                    <TipoDomicilio></TipoDomicilio>
                    <TipoAsentamiento>0</TipoAsentamiento>
                    <FechaRegistroDomicilio>2022-04-15</FechaRegistroDomicilio>
                </Domicilio>
            </Domicilios>
            <Empleos></Empleos>
            <Mensajes>
                <Mensaje>
                    <TipoMensaje>2</TipoMensaje>
                    <Leyenda>1</Leyenda>
                </Mensaje>
            </Mensajes>
            <Cuentas>
                <Cuenta>
                    <FechaActualizacion>2018-05-31</FechaActualizacion>
                    <RegistroImpugnado>0</RegistroImpugnado>
                    <ClaveOtorgante></ClaveOtorgante>
                    <NombreOtorgante>TIENDA DEPARTAMENTAL</NombreOtorgante>
                    <CuentaActual></CuentaActual>
                    <TipoResponsabilidad>I</TipoResponsabilidad>
                    <TipoCuenta>F</TipoCuenta>
                    <TipoCredito>AM</TipoCredito>
                    <ClaveUnidadMonetaria>MX</ClaveUnidadMonetaria>
                    <ValorActivoValuacion>0</ValorActivoValuacion>
                    <NumeroPagos>12</NumeroPagos>
                    <FrecuenciaPagos>M</FrecuenciaPagos>
                    <MontoPagar>0</MontoPagar>
                    <FechaAperturaCuenta>2012-05-01</FechaAperturaCuenta>
                    <FechaUltimoPago>2018-06-01</FechaUltimoPago>
                    <FechaUltimaCompra>2012-05-01</FechaUltimaCompra>
                    <FechaCierreCuenta>2018-06-01</FechaCierreCuenta>
                    <FechaReporte>2018-05-31</FechaReporte>
                    <UltimaFechaSaldoCero></UltimaFechaSaldoCero>
                    <Garantia></Garantia>
                    <CreditoMaximo>1398</CreditoMaximo>
                    <SaldoActual>0</SaldoActual>
                    <LimiteCredito>7953</LimiteCredito>
                    <SaldoVencido>0</SaldoVencido>
                    <NumeroPagosVencidos>0</NumeroPagosVencidos>
                    <PagoActual> V</PagoActual>
                    <HistoricoPagos> V----------------------------------------------</HistoricoPagos>
                    <FechaRecienteHistoricoPagos></FechaRecienteHistoricoPagos>
                    <FechaAntiguaHistoricoPagos></FechaAntiguaHistoricoPagos>
                    <ClavePrevencion>CC</ClavePrevencion>
                    <TotalPagosReportados>0</TotalPagosReportados>
                    <PeorAtraso>13</PeorAtraso>
                    <FechaPeorAtraso>2018-01-31</FechaPeorAtraso>
                    <SaldoVencidoPeorAtraso>1398</SaldoVencidoPeorAtraso>
                </Cuenta>
                <Cuenta>
                    <FechaActualizacion>2012-11-07</FechaActualizacion>
                    <RegistroImpugnado>0</RegistroImpugnado>
                    <ClaveOtorgante></ClaveOtorgante>
                    <NombreOtorgante>BANCOS</NombreOtorgante>
                    <CuentaActual></CuentaActual>
                    <TipoResponsabilidad>I</TipoResponsabilidad>
                    <TipoCuenta>F</TipoCuenta>
                    <TipoCredito>PP</TipoCredito>
                    <ClaveUnidadMonetaria>MX</ClaveUnidadMonetaria>
                    <ValorActivoValuacion>0</ValorActivoValuacion>
                    <NumeroPagos>10</NumeroPagos>
                    <FrecuenciaPagos>C</FrecuenciaPagos>
                    <MontoPagar>0</MontoPagar>
                    <FechaAperturaCuenta>2012-06-12</FechaAperturaCuenta>
                    <FechaUltimoPago>2012-10-31</FechaUltimoPago>
                    <FechaUltimaCompra>2012-06-12</FechaUltimaCompra>
                    <FechaCierreCuenta>2012-11-01</FechaCierreCuenta>
                    <FechaReporte>2012-11-07</FechaReporte>
                    <UltimaFechaSaldoCero></UltimaFechaSaldoCero>
                    <Garantia></Garantia>
                    <CreditoMaximo>6004</CreditoMaximo>
                    <SaldoActual>0</SaldoActual>
                    <LimiteCredito>6004</LimiteCredito>
                    <SaldoVencido>0</SaldoVencido>
                    <NumeroPagosVencidos>0</NumeroPagosVencidos>
                    <PagoActual> V</PagoActual>
                    <HistoricoPagos> V V-- V V</HistoricoPagos>
                    <FechaRecienteHistoricoPagos></FechaRecienteHistoricoPagos>
                    <FechaAntiguaHistoricoPagos></FechaAntiguaHistoricoPagos>
                    <ClavePrevencion>CC</ClavePrevencion>
                    <TotalPagosReportados>0</TotalPagosReportados>
                    <PeorAtraso>1</PeorAtraso>
                    <FechaPeorAtraso>2012-07-11</FechaPeorAtraso>
                    <SaldoVencidoPeorAtraso>733</SaldoVencidoPeorAtraso>
                </Cuenta>
                <Cuenta>
                    <FechaActualizacion>2014-04-25</FechaActualizacion>
                    <RegistroImpugnado>0</RegistroImpugnado>
                    <ClaveOtorgante></ClaveOtorgante>
                    <NombreOtorgante>TIENDA DEPARTAMENTAL</NombreOtorgante>
                    <CuentaActual></CuentaActual>
                    <TipoResponsabilidad>I</TipoResponsabilidad>
                    <TipoCuenta>R</TipoCuenta>
                    <TipoCredito>LC</TipoCredito>
                    <ClaveUnidadMonetaria>MX</ClaveUnidadMonetaria>
                    <ValorActivoValuacion>0</ValorActivoValuacion>
                    <NumeroPagos>3</NumeroPagos>
                    <FrecuenciaPagos>M</FrecuenciaPagos>
                    <MontoPagar>1500</MontoPagar>
                    <FechaAperturaCuenta>2011-04-03</FechaAperturaCuenta>
                    <FechaUltimoPago>2011-12-01</FechaUltimoPago>
                    <FechaUltimaCompra>2011-05-03</FechaUltimaCompra>
                    <FechaCierreCuenta>2011-12-01</FechaCierreCuenta>
                    <FechaReporte>2014-04-25</FechaReporte>
                    <UltimaFechaSaldoCero>2014-04-25</UltimaFechaSaldoCero>
                    <Garantia></Garantia>
                    <CreditoMaximo>0</CreditoMaximo>
                    <SaldoActual>0</SaldoActual>
                    <LimiteCredito>5100</LimiteCredito>
                    <SaldoVencido>200</SaldoVencido>
                    <NumeroPagosVencidos>0</NumeroPagosVencidos>
                    <PagoActual> V</PagoActual>
                    <HistoricoPagos> V----------------------------------------------</HistoricoPagos>
                    <FechaRecienteHistoricoPagos></FechaRecienteHistoricoPagos>
                    <FechaAntiguaHistoricoPagos></FechaAntiguaHistoricoPagos>
                    <ClavePrevencion></ClavePrevencion>
                    <TotalPagosReportados>0</TotalPagosReportados>
                    <PeorAtraso>0</PeorAtraso>
                    <FechaPeorAtraso></FechaPeorAtraso><SaldoVencidoPeorAtraso>0</SaldoVencidoPeorAtraso>
                </Cuenta>
                <Cuenta>
                    <FechaActualizacion>2021-12-07</FechaActualizacion>
                    <RegistroImpugnado>0</RegistroImpugnado>
                    <ClaveOtorgante></ClaveOtorgante>
                    <NombreOtorgante>BANCO</NombreOtorgante>
                    <CuentaActual></CuentaActual>
                    <TipoResponsabilidad>I</TipoResponsabilidad>
                    <TipoCuenta>R</TipoCuenta>
                    <TipoCredito>TC</TipoCredito>
                    <ClaveUnidadMonetaria>MX</ClaveUnidadMonetaria>
                    <ValorActivoValuacion></ValorActivoValuacion>
                    <NumeroPagos></NumeroPagos>
                    <FrecuenciaPagos>M</FrecuenciaPagos>
                    <MontoPagar>12539</MontoPagar>
                    <FechaAperturaCuenta>2020-10-05</FechaAperturaCuenta>
                    <FechaUltimoPago></FechaUltimoPago>
                    <FechaUltimaCompra>2020-12-08</FechaUltimaCompra>
                    <FechaCierreCuenta></FechaCierreCuenta>
                    <FechaReporte>2021-11-30</FechaReporte>
                    <UltimaFechaSaldoCero></UltimaFechaSaldoCero>
                    <Garantia></Garantia>
                    <CreditoMaximo>12538</CreditoMaximo>
                    <SaldoActual>12539</SaldoActual>
                    <LimiteCredito>9500</LimiteCredito>
                    <SaldoVencido>12539</SaldoVencido>
                    <NumeroPagosVencidos>9</NumeroPagosVencidos>
                    <PagoActual>06</PagoActual>
                    <HistoricoPagos>06060613 V0403020101 V V V--</HistoricoPagos>
                    <FechaRecienteHistoricoPagos></FechaRecienteHistoricoPagos>
                    <FechaAntiguaHistoricoPagos></FechaAntiguaHistoricoPagos>
                    <ClavePrevencion>UP</ClavePrevencion>
                    <TotalPagosReportados></TotalPagosReportados>
                    <PeorAtraso>13</PeorAtraso>
                    <FechaPeorAtraso></FechaPeorAtraso>
                    <SaldoVencidoPeorAtraso>0</SaldoVencidoPeorAtraso>
                </Cuenta>
            </Cuentas>
            <ConsultasEfectuadas>
                <ConsultaEfectuada>
                    <FechaConsulta>2022-01-04</FechaConsulta>
                    <ClaveOtorgante></ClaveOtorgante>
                    <NombreOtorgante>PODEMOS</NombreOtorgante>
                    <TelefonoOtorgante>55-4129-762</TelefonoOtorgante>
                    <TipoCredito>F</TipoCredito>
                    <ClaveUnidadMonetaria>MX</ClaveUnidadMonetaria>
                    <ImporteCredito>5000</ImporteCredito>
                    <TipoResponsabilidad></TipoResponsabilidad>
                    </ConsultaEfectuada><ConsultaEfectuada>
                    <FechaConsulta>2020-10-05</FechaConsulta>
                    <ClaveOtorgante></ClaveOtorgante>
                    <NombreOtorgante>SIC</NombreOtorgante>
                    <TipoCredito>F</TipoCredito>
                    <ClaveUnidadMonetaria>MX</ClaveUnidadMonetaria>
                    <ImporteCredito>0</ImporteCredito>
                    <TipoResponsabilidad></TipoResponsabilidad>
                </ConsultaEfectuada>
                <ConsultaEfectuada>
                    <FechaConsulta>2020-10-05</FechaConsulta>
                    <ClaveOtorgante></ClaveOtorgante>
                    <NombreOtorgante>BANCO</NombreOtorgante>
                    <TipoCredito>NC</TipoCredito>
                    <ClaveUnidadMonetaria></ClaveUnidadMonetaria>
                    <ImporteCredito>0</ImporteCredito>
                    <TipoResponsabilidad>I</TipoResponsabilidad>
                </ConsultaEfectuada>
                <ConsultaEfectuada>
                    <FechaConsulta>2020-10-05</FechaConsulta>
                    <ClaveOtorgante></ClaveOtorgante>
                    <NombreOtorgante>BANCO</NombreOtorgante>
                    <TipoCredito>NC</TipoCredito>
                    <ClaveUnidadMonetaria></ClaveUnidadMonetaria>
                    <ImporteCredito>0</ImporteCredito>
                    <TipoResponsabilidad>I</TipoResponsabilidad>
                </ConsultaEfectuada>
            </ConsultasEfectuadas>
            <DeclaracionesConsumidor></DeclaracionesConsumidor>
            </Persona>
        </Personas>
    </Respuesta>"""


XML_TEST_NO_ACCOUNTS = """<?xml version="1.0" encoding = "ISO-8859-1"?>
    <Respuesta xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/Respuesta.xsd">
    <Personas>
        <Persona>
            <Encabezado>
                <FolioConsultaOtorgante>00HXQ2PPP23237220104003</FolioConsultaOtorgante>
                <ClaveOtorgante>000997</ClaveOtorgante><ExpedienteEncontrado>1</ExpedienteEncontrado>
                <FolioConsulta>876657434</FolioConsulta>
            </Encabezado>
            <Nombre>
                <ApellidoPaterno>PRUEBA</ApellidoPaterno>
                <ApellidoMaterno>PRUEBA</ApellidoMaterno>
                <ApellidoAdicional></ApellidoAdicional>
                <Nombres>LIDIA</Nombres>
                <FechaNacimiento>1981-01-10</FechaNacimiento>
                <RFC>OMMN9444053L6</RFC>
                <CURP>OMMN944405MDFRDN05</CURP>
                <Nacionalidad></Nacionalidad>
                <Residencia>5</Residencia>
                <EstadoCivil></EstadoCivil>
                <Sexo></Sexo>
                <ClaveElectorIFE></ClaveElectorIFE>
                <NumeroDependientes>2</NumeroDependientes>
                <FechaDefuncion></FechaDefuncion>
            </Nombre>
            <Domicilios>
                <Domicilio>
                    <Direccion>CDA MONTE DE LOS SAUCES</Direccion>
                    <ColoniaPoblacion>jesus del monte</ColoniaPoblacion>
                    <DelegacionMunicipio>CUAJIMALPA</DelegacionMunicipio>
                    <Ciudad>MEXICO</Ciudad>
                    <Estado>DF</Estado>
                    <CP>22891</CP>
                    <FechaResidencia>2022-01-04</FechaResidencia>
                    <NumeroTelefono></NumeroTelefono>
                    <TipoDomicilio></TipoDomicilio>
                    <TipoAsentamiento></TipoAsentamiento>
                    <FechaRegistroDomicilio>2022-01-04</FechaRegistroDomicilio>
                </Domicilio>
                <Domicilio>
                    <Direccion>C SN BORJA 119 </Direccion>
                    <ColoniaPoblacion>JOSEFA ORTIZ DE DOMINGUEZ</ColoniaPoblacion>
                    <DelegacionMunicipio>ENSENADA</DelegacionMunicipio>
                    <Ciudad></Ciudad>
                    <Estado>BC</Estado>
                    <CP>22891</CP>
                    <FechaResidencia>2021-06-24</FechaResidencia>
                    <NumeroTelefono></NumeroTelefono>
                    <TipoDomicilio></TipoDomicilio>
                    <TipoAsentamiento>0</TipoAsentamiento>
                    <FechaRegistroDomicilio>2021-06-24</FechaRegistroDomicilio>
                </Domicilio>
                <Domicilio>
                    <Direccion>C SAN BORJA 119</Direccion>
                    <ColoniaPoblacion>COL JOSEFA ORTIZ DE DOMINGUEZ</ColoniaPoblacion>
                    <DelegacionMunicipio>ENSENADA B C</DelegacionMunicipio>
                    <Ciudad></Ciudad>
                    <Estado>BC</Estado>
                    <CP>22891</CP>
                    <FechaResidencia>2018-04-15</FechaResidencia>
                    <NumeroTelefono></NumeroTelefono>
                    <TipoDomicilio></TipoDomicilio>
                    <TipoAsentamiento>0</TipoAsentamiento>
                    <FechaRegistroDomicilio>2022-04-15</FechaRegistroDomicilio>
                </Domicilio>
                <Domicilio>
                    <Direccion>INSURGENTES SUR 1007</Direccion>
                    <ColoniaPoblacion>INSURGENTES</ColoniaPoblacion>
                    <DelegacionMunicipio>BENITO JUAREZ</DelegacionMunicipio>
                    <Ciudad>BENITO JUAREZ</Ciudad>
                    <Estado>BC</Estado>
                    <CP>22891</CP>
                    <FechaResidencia>2018-04-15</FechaResidencia>
                    <NumeroTelefono></NumeroTelefono>
                    <TipoDomicilio></TipoDomicilio>
                    <TipoAsentamiento>0</TipoAsentamiento>
                    <FechaRegistroDomicilio>2022-04-15</FechaRegistroDomicilio>
                </Domicilio>
            </Domicilios>
            <Empleos></Empleos>
            <Mensajes>
                <Mensaje>
                    <TipoMensaje>2</TipoMensaje>
                    <Leyenda>1</Leyenda>
                </Mensaje>
            </Mensajes>
            <Cuentas>
            </Cuentas>
            <ConsultasEfectuadas>
                <ConsultaEfectuada>
                    <FechaConsulta>2022-01-04</FechaConsulta>
                    <ClaveOtorgante></ClaveOtorgante>
                    <NombreOtorgante>PODEMOS</NombreOtorgante>
                    <TelefonoOtorgante>55-4129-762</TelefonoOtorgante>
                    <TipoCredito>F</TipoCredito>
                    <ClaveUnidadMonetaria>MX</ClaveUnidadMonetaria>
                    <ImporteCredito>5000</ImporteCredito>
                    <TipoResponsabilidad></TipoResponsabilidad>
                    </ConsultaEfectuada><ConsultaEfectuada>
                    <FechaConsulta>2020-10-05</FechaConsulta>
                    <ClaveOtorgante></ClaveOtorgante>
                    <NombreOtorgante>SIC</NombreOtorgante>
                    <TipoCredito>F</TipoCredito>
                    <ClaveUnidadMonetaria>MX</ClaveUnidadMonetaria>
                    <ImporteCredito>0</ImporteCredito>
                    <TipoResponsabilidad></TipoResponsabilidad>
                </ConsultaEfectuada>
                <ConsultaEfectuada>
                    <FechaConsulta>2020-10-05</FechaConsulta>
                    <ClaveOtorgante></ClaveOtorgante>
                    <NombreOtorgante>BANCO</NombreOtorgante>
                    <TipoCredito>NC</TipoCredito>
                    <ClaveUnidadMonetaria></ClaveUnidadMonetaria>
                    <ImporteCredito>0</ImporteCredito>
                    <TipoResponsabilidad>I</TipoResponsabilidad>
                </ConsultaEfectuada>
                <ConsultaEfectuada>
                    <FechaConsulta>2020-10-05</FechaConsulta>
                    <ClaveOtorgante></ClaveOtorgante>
                    <NombreOtorgante>BANCO</NombreOtorgante>
                    <TipoCredito>NC</TipoCredito>
                    <ClaveUnidadMonetaria></ClaveUnidadMonetaria>
                    <ImporteCredito>0</ImporteCredito>
                    <TipoResponsabilidad>I</TipoResponsabilidad>
                </ConsultaEfectuada>
            </ConsultasEfectuadas>
            <DeclaracionesConsumidor></DeclaracionesConsumidor>
            </Persona>
        </Personas>
    </Respuesta>"""

XML_TEST_ONE_ITEM = """<?xml version="1.0" encoding = "ISO-8859-1"?>
    <Respuesta xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/Respuesta.xsd">
    <Personas>
        <Persona>
            <Encabezado>
                <FolioConsultaOtorgante>00HXQ2PPP23237220104003</FolioConsultaOtorgante>
                <ClaveOtorgante>000997</ClaveOtorgante><ExpedienteEncontrado>1</ExpedienteEncontrado>
                <FolioConsulta>876657434</FolioConsulta>
            </Encabezado>
            <Nombre>
                <ApellidoPaterno>PRUEBA</ApellidoPaterno>
                <ApellidoMaterno>PRUEBA</ApellidoMaterno>
                <ApellidoAdicional></ApellidoAdicional>
                <Nombres>ONE</Nombres>
                <FechaNacimiento>1981-01-10</FechaNacimiento>
                <RFC>OMMN9444053L6</RFC>
                <CURP>OMMN944405MDFRDN05</CURP>
                <Nacionalidad></Nacionalidad>
                <Residencia>5</Residencia>
                <EstadoCivil></EstadoCivil>
                <Sexo></Sexo>
                <ClaveElectorIFE></ClaveElectorIFE>
                <NumeroDependientes>2</NumeroDependientes>
                <FechaDefuncion></FechaDefuncion>
            </Nombre>
            <Domicilios></Domicilios>
            <Empleos></Empleos>
            <Mensajes>
                <Mensaje>
                    <TipoMensaje>2</TipoMensaje>
                    <Leyenda>1</Leyenda>
                </Mensaje>
            </Mensajes>
            <Cuentas>
                <Cuenta>
                    <FechaActualizacion>2018-05-31</FechaActualizacion>
                    <RegistroImpugnado>0</RegistroImpugnado>
                    <ClaveOtorgante></ClaveOtorgante>
                    <NombreOtorgante>TIENDA DEPARTAMENTAL</NombreOtorgante>
                    <CuentaActual></CuentaActual>
                    <TipoResponsabilidad>I</TipoResponsabilidad>
                    <TipoCuenta>F</TipoCuenta>
                    <TipoCredito>AM</TipoCredito>
                    <ClaveUnidadMonetaria>MX</ClaveUnidadMonetaria>
                    <ValorActivoValuacion>0</ValorActivoValuacion>
                    <NumeroPagos>12</NumeroPagos>
                    <FrecuenciaPagos>M</FrecuenciaPagos>
                    <MontoPagar>0</MontoPagar>
                    <FechaAperturaCuenta>2012-05-01</FechaAperturaCuenta>
                    <FechaUltimoPago>2018-06-01</FechaUltimoPago>
                    <FechaUltimaCompra>2012-05-01</FechaUltimaCompra>
                    <FechaCierreCuenta>2018-06-01</FechaCierreCuenta>
                    <FechaReporte>2018-05-31</FechaReporte>
                    <UltimaFechaSaldoCero></UltimaFechaSaldoCero>
                    <Garantia></Garantia>
                    <CreditoMaximo>1398</CreditoMaximo>
                    <SaldoActual>0</SaldoActual>
                    <LimiteCredito>7953</LimiteCredito>
                    <SaldoVencido>0</SaldoVencido>
                    <NumeroPagosVencidos>0</NumeroPagosVencidos>
                    <PagoActual> V</PagoActual>
                    <HistoricoPagos> V----------------------------------------------</HistoricoPagos>
                    <FechaRecienteHistoricoPagos></FechaRecienteHistoricoPagos>
                    <FechaAntiguaHistoricoPagos></FechaAntiguaHistoricoPagos>
                    <ClavePrevencion>CC</ClavePrevencion>
                    <TotalPagosReportados>0</TotalPagosReportados>
                    <PeorAtraso>13</PeorAtraso>
                    <FechaPeorAtraso>2018-01-31</FechaPeorAtraso>
                    <SaldoVencidoPeorAtraso>1398</SaldoVencidoPeorAtraso>
                </Cuenta>
            </Cuentas>
            <ConsultasEfectuadas>
                <ConsultaEfectuada>
                    <FechaConsulta>2022-01-04</FechaConsulta>
                    <ClaveOtorgante></ClaveOtorgante>
                    <NombreOtorgante>PODEMOS</NombreOtorgante>
                    <TelefonoOtorgante>55-4129-762</TelefonoOtorgante>
                    <TipoCredito>F</TipoCredito>
                    <ClaveUnidadMonetaria>MX</ClaveUnidadMonetaria>
                    <ImporteCredito>5000</ImporteCredito>
                    <TipoResponsabilidad></TipoResponsabilidad>
                </ConsultaEfectuada>
            </ConsultasEfectuadas>
            <DeclaracionesConsumidor></DeclaracionesConsumidor>
            </Persona>
        </Personas>
    </Respuesta>"""

XML_TEST_ERROR = """<?xml version="1.0" encoding="ISO-8859-1"?>
    <Error xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/Error.xsd">
	    <ClaveOtorgante>0000081008</ClaveOtorgante>
	    <FolioConsultaOtorgante>00001P</FolioConsultaOtorgante>
	    <ProductoRequerido>9</ProductoRequerido>
	    <Errores>
		    <DescripcionError>La longitud del RFC no es valida</DescripcionError>
		    <DescripcionError>La longitud de la nacionalidad no es valida</DescripcionError>
	    </Errores>
    </Error>"""


XML_TEST_EVALUATIONS_RULES = """<?xml version="1.0" encoding = "ISO-8859-1"?>
    <Respuesta xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/Respuesta.xsd">
    <Personas>
        <Persona>
            <Encabezado>
                <FolioConsultaOtorgante>00HXQ2PPP23237220104003</FolioConsultaOtorgante>
                <ClaveOtorgante>000997</ClaveOtorgante><ExpedienteEncontrado>1</ExpedienteEncontrado>
                <FolioConsulta>876657434</FolioConsulta>
            </Encabezado>
            <Nombre>
                <ApellidoPaterno>MARQUEZ</ApellidoPaterno>
                <ApellidoMaterno>VERA</ApellidoMaterno>
                <ApellidoAdicional></ApellidoAdicional>
                <Nombres>KARLA RUBY</Nombres>
                <FechaNacimiento>2003-07-10</FechaNacimiento>
                <RFC>MAVK030710K54</RFC>
                <CURP>MAVK030710MDFRRRA3</CURP>
                <Nacionalidad>MEXICANA</Nacionalidad>
                <Residencia>5</Residencia>
                <EstadoCivil></EstadoCivil>
                <Sexo></Sexo>
                <ClaveElectorIFE></ClaveElectorIFE>
                <NumeroDependientes>2</NumeroDependientes>
                <FechaDefuncion></FechaDefuncion>
            </Nombre>
            <Domicilios>
                <Domicilio>
                    <Direccion>Diagonal #16</Direccion>
                    <ColoniaPoblacion>San Fernando</ColoniaPoblacion>
                    <DelegacionMunicipio>Huixquilucan de Degollado</DelegacionMunicipio>
                    <Ciudad>Mexico</Ciudad>
                    <Estado>Mexico</Estado>
                    <CP>52765</CP>
                    <FechaResidencia>2022-01-04</FechaResidencia>
                    <NumeroTelefono></NumeroTelefono>
                    <TipoDomicilio></TipoDomicilio>
                    <TipoAsentamiento></TipoAsentamiento>
                    <FechaRegistroDomicilio>2022-01-04</FechaRegistroDomicilio>
                </Domicilio>
                <Domicilio>
                    <Direccion>Cda Polvora C 81</Direccion>
                    <ColoniaPoblacion>San Fernando</ColoniaPoblacion>
                    <DelegacionMunicipio>Huixquilucan de Degollado</DelegacionMunicipio>
                    <Ciudad>Mexico</Ciudad>
                    <Estado>Mexico</Estado>
                    <CP>52765</CP>
                    <FechaResidencia>2021-06-24</FechaResidencia>
                    <NumeroTelefono></NumeroTelefono>
                    <TipoDomicilio></TipoDomicilio>
                    <TipoAsentamiento>0</TipoAsentamiento>
                    <FechaRegistroDomicilio>2021-06-24</FechaRegistroDomicilio>
                </Domicilio>
                <Domicilio>
                    <Direccion>Porfirio Diaz Norte # 47</Direccion>
                    <ColoniaPoblacion>Buenavista</ColoniaPoblacion>
                    <DelegacionMunicipio>Nicolas Romero</DelegacionMunicipio>
                    <Ciudad>Mexico</Ciudad>
                    <Estado>Mexico</Estado>
                    <CP>54414</CP>
                    <FechaResidencia>2018-04-15</FechaResidencia>
                    <NumeroTelefono></NumeroTelefono>
                    <TipoDomicilio></TipoDomicilio>
                    <TipoAsentamiento>0</TipoAsentamiento>
                    <FechaRegistroDomicilio>2022-04-15</FechaRegistroDomicilio>
                </Domicilio>
                <Domicilio>
                    <Direccion>Azaleas 5 2</Direccion>
                    <ColoniaPoblacion>Vista Hermosa</ColoniaPoblacion>
                    <DelegacionMunicipio>Nicolas Romero</DelegacionMunicipio>
                    <Ciudad>Mexico</Ciudad>
                    <Estado>Mexico</Estado>
                    <CP>54414</CP>
                    <FechaResidencia>2018-04-15</FechaResidencia>
                    <NumeroTelefono></NumeroTelefono>
                    <TipoDomicilio></TipoDomicilio>
                    <TipoAsentamiento>0</TipoAsentamiento>
                    <FechaRegistroDomicilio>2022-04-15</FechaRegistroDomicilio>
                </Domicilio>
            </Domicilios>
            <Empleos></Empleos>
            <Mensajes>
                <Mensaje>
                    <TipoMensaje>2</TipoMensaje>
                    <Leyenda>1</Leyenda>
                </Mensaje>
            </Mensajes>
            <Cuentas>
                <Cuenta>
                    <FechaActualizacion>2014-04-25</FechaActualizacion>
                    <RegistroImpugnado>0</RegistroImpugnado>
                    <ClaveOtorgante></ClaveOtorgante>
                    <NombreOtorgante>TIENDA DEPARTAMENTAL</NombreOtorgante>
                    <CuentaActual></CuentaActual>
                    <TipoResponsabilidad>I</TipoResponsabilidad>
                    <TipoCuenta>R</TipoCuenta>
                    <TipoCredito>LC</TipoCredito>
                    <ClaveUnidadMonetaria>MX</ClaveUnidadMonetaria>
                    <ValorActivoValuacion>0</ValorActivoValuacion>
                    <NumeroPagos>3</NumeroPagos>
                    <FrecuenciaPagos>M</FrecuenciaPagos>
                    <MontoPagar>1500</MontoPagar>
                    <FechaAperturaCuenta>2022-05-01</FechaAperturaCuenta>
                    <FechaUltimoPago>2022-06-01</FechaUltimoPago>
                    <FechaUltimaCompra>2011-05-03</FechaUltimaCompra>
                    <FechaCierreCuenta>2011-12-01</FechaCierreCuenta>
                    <FechaReporte>2014-04-25</FechaReporte>
                    <UltimaFechaSaldoCero>2014-04-25</UltimaFechaSaldoCero>
                    <Garantia></Garantia>
                    <CreditoMaximo>0</CreditoMaximo>
                    <SaldoActual>0</SaldoActual>
                    <LimiteCredito>5100</LimiteCredito>
                    <SaldoVencido>3499</SaldoVencido>
                    <NumeroPagosVencidos>0</NumeroPagosVencidos>
                    <PagoActual> V</PagoActual>
                    <HistoricoPagos> V----------------------------------------------</HistoricoPagos>
                    <FechaRecienteHistoricoPagos></FechaRecienteHistoricoPagos>
                    <FechaAntiguaHistoricoPagos></FechaAntiguaHistoricoPagos>
                    <ClavePrevencion>UP</ClavePrevencion>
                    <TotalPagosReportados>0</TotalPagosReportados>
                    <PeorAtraso>0</PeorAtraso>
                    <FechaPeorAtraso></FechaPeorAtraso><SaldoVencidoPeorAtraso>0</SaldoVencidoPeorAtraso>
                </Cuenta>
                <Cuenta>
                    <FechaActualizacion>2021-12-07</FechaActualizacion>
                    <RegistroImpugnado>0</RegistroImpugnado>
                    <ClaveOtorgante></ClaveOtorgante>
                    <NombreOtorgante>BANCO</NombreOtorgante>
                    <CuentaActual></CuentaActual>
                    <TipoResponsabilidad>I</TipoResponsabilidad>
                    <TipoCuenta>R</TipoCuenta>
                    <TipoCredito>TC</TipoCredito>
                    <ClaveUnidadMonetaria>MX</ClaveUnidadMonetaria>
                    <ValorActivoValuacion></ValorActivoValuacion>
                    <NumeroPagos></NumeroPagos>
                    <FrecuenciaPagos>M</FrecuenciaPagos>
                    <MontoPagar>12539</MontoPagar>
                    <FechaAperturaCuenta>2022-08-01</FechaAperturaCuenta>
                    <FechaUltimoPago></FechaUltimoPago>
                    <FechaUltimaCompra>2020-12-08</FechaUltimaCompra>
                    <FechaCierreCuenta></FechaCierreCuenta>
                    <FechaReporte>2021-11-30</FechaReporte>
                    <UltimaFechaSaldoCero></UltimaFechaSaldoCero>
                    <Garantia></Garantia>
                    <CreditoMaximo>12538</CreditoMaximo>
                    <SaldoActual>12539</SaldoActual>
                    <LimiteCredito>9500</LimiteCredito>
                    <SaldoVencido>3499</SaldoVencido>
                    <NumeroPagosVencidos>9</NumeroPagosVencidos>
                    <PagoActual>06</PagoActual>
                    <HistoricoPagos>06060613 V0403020101 V V V--</HistoricoPagos>
                    <FechaRecienteHistoricoPagos></FechaRecienteHistoricoPagos>
                    <FechaAntiguaHistoricoPagos></FechaAntiguaHistoricoPagos>
                    <ClavePrevencion>CC</ClavePrevencion>
                    <TotalPagosReportados></TotalPagosReportados>
                    <PeorAtraso>13</PeorAtraso>
                    <FechaPeorAtraso></FechaPeorAtraso>
                    <SaldoVencidoPeorAtraso>0</SaldoVencidoPeorAtraso>
                </Cuenta>
            </Cuentas>
            <ConsultasEfectuadas>
                <ConsultaEfectuada>
                    <FechaConsulta>2022-01-04</FechaConsulta>
                    <ClaveOtorgante></ClaveOtorgante>
                    <NombreOtorgante>PODEMOS</NombreOtorgante>
                    <TelefonoOtorgante>55-4129-762</TelefonoOtorgante>
                    <TipoCredito>F</TipoCredito>
                    <ClaveUnidadMonetaria>MX</ClaveUnidadMonetaria>
                    <ImporteCredito>5000</ImporteCredito>
                    <TipoResponsabilidad></TipoResponsabilidad>
                    </ConsultaEfectuada><ConsultaEfectuada>
                    <FechaConsulta>2020-10-05</FechaConsulta>
                    <ClaveOtorgante></ClaveOtorgante>
                    <NombreOtorgante>SIC</NombreOtorgante>
                    <TipoCredito>F</TipoCredito>
                    <ClaveUnidadMonetaria>MX</ClaveUnidadMonetaria>
                    <ImporteCredito>0</ImporteCredito>
                    <TipoResponsabilidad></TipoResponsabilidad>
                </ConsultaEfectuada>
                <ConsultaEfectuada>
                    <FechaConsulta>2020-10-05</FechaConsulta>
                    <ClaveOtorgante></ClaveOtorgante>
                    <NombreOtorgante>BANCO</NombreOtorgante>
                    <TipoCredito>NC</TipoCredito>
                    <ClaveUnidadMonetaria></ClaveUnidadMonetaria>
                    <ImporteCredito>0</ImporteCredito>
                    <TipoResponsabilidad>I</TipoResponsabilidad>
                </ConsultaEfectuada>
                <ConsultaEfectuada>
                    <FechaConsulta>2020-10-05</FechaConsulta>
                    <ClaveOtorgante></ClaveOtorgante>
                    <NombreOtorgante>BANCO</NombreOtorgante>
                    <TipoCredito>NC</TipoCredito>
                    <ClaveUnidadMonetaria></ClaveUnidadMonetaria>
                    <ImporteCredito>0</ImporteCredito>
                    <TipoResponsabilidad>I</TipoResponsabilidad>
                </ConsultaEfectuada>
            </ConsultasEfectuadas>
            <DeclaracionesConsumidor></DeclaracionesConsumidor>
            </Persona>
        </Personas>
    </Respuesta>"""
